import tkinter as tk
window = tk.Tk()
window.title("Multi-Widget GUI Example")
window.geometry("400x300+10+10")
name_label = tk.Label(window, text="Name:")
name_label.grid(row=0, column=0, sticky="w")
name_entry = tk.Entry(window)
name_entry.grid(row=0, column=1)
age_label = tk.Label(window, text="Age:")
age_label.grid(row=1, column=0, sticky="w")
age_entry = tk.Entry(window)
age_entry.grid(row=1, column=1)
phone_label = tk.Label(window, text="Phone:")
phone_label.grid(row=2, column=0, sticky="w")
phone_entry = tk.Entry(window)
phone_entry.grid(row=2, column=1)
gender_label = tk.Label(window, text="Gender:")
gender_label.grid(row=3, column=0, sticky="w")
male_button = tk.Radiobutton(window, text="Male", value="male")
male_button.grid(row=3, column=1, sticky="w")
female_button = tk.Radiobutton(window, text="Female", value="female")
female_button.grid(row=3, column=1, sticky="e")
button = tk.Button(window, text="Submit")
button.grid(row=4, column=0, columnspan=2)
window.mainloop()
